version: 0.0
os: linux
files:
  # This section is generally not needed for ECR-based deployments
  # as CodeDeploy doesn't directly copy files from the artifact.
  # You might include it if you have other configuration files to deploy.
  - source: build-artifacts-$BUILD_VERSION.zip
    destination: /tmp/codedeploy-artifact # Example destination for the build artifact

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ubuntu # Or your web server user

  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/run_container.sh
      timeout: 600 # Increased timeout as container startup might take longer
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_container.sh # Ensure container is stopped on stop deployment
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh # Optional health check script
      timeout: 300
      runas: ubuntu